apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-http-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-http
  template:
    metadata:
      labels:
        app: java-http
    spec:
      containers:
      - name: java-http
        image: IMAGE_PLACEHOLDER   # Jenkins will replace this with ECR image
        ports:
        - containerPort: 8080
